/*
  Warnings:

  - You are about to alter the column `id` on the `product` table. The data in that column will be cast from `BigInt` to `Int`. This cast may fail. Please make sure the data in the column can be cast.

*/
-- RedefineTables
CREATE TABLE "_prisma_new_product" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "title" STRING NOT NULL,
    "description" STRING NOT NULL,
    "image_link" STRING NOT NULL,
    "img_alt_text" STRING NOT NULL,
    "isVisible" BOOL NOT NULL,
    "isAvailable" BOOL NOT NULL,

    CONSTRAINT "product_pkey" PRIMARY KEY ("id")
);
INSERT INTO "_prisma_new_product" ("description","id","image_link","img_alt_text","isAvailable","isVisible","title") SELECT "description","id","image_link","img_alt_text","isAvailable","isVisible","title" FROM "product";
DROP TABLE "product" CASCADE;
ALTER TABLE "_prisma_new_product" RENAME TO "product";
